---
title: "Assignment1"
author: "Cesar L. Espitia"
date: "1/29/2018"
output:
  html_document: default
  pdf_document: default
---

## 1. Problem Set 1

Netflix assignemnt.

1. Calculate the dot product u.v where u = [0.5; 0.5] and v = [3;-4]
```{r prob1-1}
u = c(0.5,0.5)
v = c(3,-4)
u%*%v

#The answer is -0.5
```
2. What are the lengths of u and v.

```{r prob1-2}
v = c(3,-4)
sqrt(v%*%v)

#The answer is 5.0 for the length of v

u = c(0.5,0.5)
sqrt(u%*%u)

#The answer is 0.707 for the length of u
```

3. What is the linear combination of 3u-2v?

```{r prob1-3}
u = c(0.5,0.5)
v = c(3,-4)
3*u - 2*v

#the answer is vector [-4.5 9.5]
```

4. What is the angle between u and v

Equation is cos(theta) = u.v / ||u||*||v||

```{r prob1-4}
dot = u%*%v
magu = sqrt(u%*%u)
magv = sqrt(v%*%v)
costheta = dot / (magu * magv)

acos(costheta)

#the angle is 1.713 radians
```

## Solving a system of equations using R only not built in functions

```{r prob2-1}
A = matrix(c(1,2,-1,1,-1,-2,3,5,4), nrow=3, ncol=3)
b = matrix(c(1, 2, 6), nrow = 3)

calc <- function (A,b){
full = cbind(A,b)

i=1
j=1

#part 1
while (i <= nrow(full)-1){
  c = full[i+1,j]/full[j,j]
  full[i+1,] = full[i+1,]-c*full[j,]
  i = 1+i
}

i=2
j=2
#part 2
while (i <= nrow(full)-1){
  c = full[i+1,j]/full[j,j]
  full[i+1,] = full[i+1,]-c*full[j,]
  i = 1+i
}

x3 = full[j+1,j+2]/full[j+1,j+1]
x2 = (full[j,j+2] - full[j,j+1]*x3)/full[j,j]
x1 = (full[j-1,j+2] - full[j-1,j+1]*x3 - full[j-1,j]*x2 )/full[j-1,j-1]

sol = cbind(x1, x2, x3)
return(sol)
}

calc(A,b)
```

